services:
  # Our PostgreSQL database
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/blog-db
      POSTGRES_DB: blog-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080